/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula1;

import javax.swing.JOptionPane;


/**
 *
 * @author Madianita Bogo
 */
public class FormVenda extends javax.swing.JFrame {
    double globalValor;
        
    public FormVenda() {
        initComponents();
    }
    
    public void efetivarVenda(){
        taSaida.append(cbxProduto.getSelectedItem().toString());
        String cores = "\nCores selecionadas: ";
        if (chkAzul.isSelected()){
            cores += "azul  ";
        }
        if (chkVermelho.isSelected()){
            cores += "vermelho  ";
        }
        if (chkPreto.isSelected()){
            cores += "preto ";
        }
        taSaida.append(cores);
                if (rbComImagem.isSelected()){
            taSaida.append("\nCom imagem!");
        }
        else{
            taSaida.append("\nSem imagem!");
        }
                taSaida.append("\nQuantidade: " + tfQtd.getText());
        taSaida.append("\nValor: " + globalValor +"\n------\n");
    }
    
    public void calcularValor(){
        
//        if (cbxProduto.getSelectedIndex() == 0) {
//            globalValor = 25.00;
//        }
//        else{
//            globalValor = 20.00;
//        }

        //Pegar a String selecionada da caixa de combinação
        String prod = cbxProduto.getSelectedItem().toString();
        if (prod.equals("Boné")) {
            globalValor = 25.00;
        }
        else{
            globalValor = 20.00;
        }
        
        if (chkAzul.isSelected()){
            globalValor += 2.0;
        }
        
        if (chkPreto.isSelected()){
            globalValor += 2.0;
        }
        
        if (chkVermelho.isSelected()){
            globalValor += 2.0;
        }
        
        if (rbComImagem.isSelected()){
             globalValor += 5.0;
        }
        
//         globalValor = globalValor * qtdade;
//         globalValor  *= qtdade;
         JOptionPane.showMessageDialog(null, tfQtd.getText());
            globalValor *= Double.parseDouble(tfQtd.getText());
            
            //tfValor.setText(Double.toString(globalValor));
             tfValor.setText(globalValor+"");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoImagem = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbxProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        chkPreto = new javax.swing.JCheckBox();
        chkVermelho = new javax.swing.JCheckBox();
        chkAzul = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tfQtd = new javax.swing.JTextField();
        rbSemImagem = new javax.swing.JRadioButton();
        rbComImagem = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        btnCalcula = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        btnEfetivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Produto:");

        cbxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boné", "Camiseta" }));

        jLabel2.setText("Cor(es) do texto:");

        chkPreto.setText("Preto");

        chkVermelho.setText("Vermelho");

        chkAzul.setText("Azul");
        chkAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAzulActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade:");

        tfQtd.setText("1");
        tfQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdActionPerformed(evt);
            }
        });

        grupoImagem.add(rbSemImagem);
        rbSemImagem.setSelected(true);
        rbSemImagem.setText("Sem Imagem");
        rbSemImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSemImagemActionPerformed(evt);
            }
        });

        grupoImagem.add(rbComImagem);
        rbComImagem.setText("Com Imagem");
        rbComImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComImagemActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor:");

        tfValor.setEnabled(false);
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        btnCalcula.setText("Calcula Valor");
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos vendidos:"));

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        btnEfetivar.setText("Efetivar Venda");
        btnEfetivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfetivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbSemImagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbComImagem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcula))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPreto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkVermelho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnEfetivar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chkPreto)
                    .addComponent(chkVermelho)
                    .addComponent(chkAzul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSemImagem)
                    .addComponent(rbComImagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcula))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnEfetivar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  
    private void rbComImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbComImagemActionPerformed

    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
          calcularValor();
    }//GEN-LAST:event_btnCalculaActionPerformed

  private void chkAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAzulActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_chkAzulActionPerformed

  private void rbSemImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSemImagemActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_rbSemImagemActionPerformed

  private void btnEfetivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfetivarActionPerformed
      efetivarVenda();
  }//GEN-LAST:event_btnEfetivarActionPerformed

  private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfValorActionPerformed

    private void tfQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcula;
    private javax.swing.JButton btnEfetivar;
    private javax.swing.JComboBox<String> cbxProduto;
    private javax.swing.JCheckBox chkAzul;
    private javax.swing.JCheckBox chkPreto;
    private javax.swing.JCheckBox chkVermelho;
    private javax.swing.ButtonGroup grupoImagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbComImagem;
    private javax.swing.JRadioButton rbSemImagem;
    private javax.swing.JTextArea taSaida;
    private javax.swing.JTextField tfQtd;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
